---
ssh: &ssh
  username: root
  password: vagrant

machines:
- name: k8s-master
  box: packer/centos72
  mem: 2048 
  cpu: 2
  gui: False
  controller: SATA Controller
  hostname: k8s-master
  ssh: *ssh
  private_network:
    ip: 10.34.57.11
  shell: |
    yum install -y salt-master salt-minion
    yum install -y git vim svn tig ctags
    mv /etc/salt{,.bak}
    mkdir -p /vagrant/repos
    #git clone https://github.com/OpstackXyz/salt.git /vagrant/repos/salt
    ln -s /vagrant/repos/salt/salt/etc /etc/salt
    ln -s /vagrant/repos/salt/salt/srv/salt /srv/salt
    systemctl start salt-master
    systemctl start salt-minion
- name: k8s-node-1
  box: packer/centos72
  mem: 2048 
  cpu: 2
  gui: False
  controller: SATA Controller
  hostname: k8s-node-1
  ssh: *ssh
  private_network:
    ip: 10.34.57.12
  shell: |
    yum install -y salt-minion
    mv /etc/salt{,.bak}
    mkdir -p /etc/salt
    echo "master: 10.34.57.11" > /etc/salt/minion
    echo "k8s-node-1.test.salt.saltops.xyz" >> /etc/salt/minion
    systemctl start salt-minion
