---
ssh: &ssh
  username: vagrant
  password: vagrant

machines:
- name: rancher01
  box: packer/centos7
  ssh: *ssh
  private_network:
    ip: 10.34.57.11
  shell: |
    yum install -y git vim svn tig ctags
- name: rancher02
  box: packer/centos7
  ssh: *ssh
  private_network:
    ip: 10.34.57.12
  shell: |
    yum install -y git vim svn tig ctags
- name: rancher03
  box: packer/centos7
  ssh: *ssh
  private_network:
    ip: 10.34.57.13
  shell: |
    yum install -y git vim svn tig ctags
