---
ssh: &ssh
  username: root
  password: vagrant

machines:
- name: k8s-master
  box: packer/centos7
  mem: 2048 
  cpu: 2
  gui: False
  controller: SATA Controller
  hostname: k8s-master
  ssh: *ssh
  private_network:
    ip: 10.34.57.11
  shell: |
    yum install -y git vim svn tig ctags
- name: k8s-node-1
  box: packer/centos7
  mem: 2048 
  cpu: 2
  gui: False
  controller: SATA Controller
  hostname: k8s-node-1
  ssh: *ssh
  private_network:
    ip: 10.34.57.12
  shell: |
    yum install -y git vim svn tig ctags
